name: RELEASE

on:
  release:
    types: [ published ]

jobs:
  release:
    name: Build and Push Frontend Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Log in to ghcr
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Frontend Metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/invenira/frontend

      - name: Build and Push Frontend Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}