name: RELEASE

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  release:
    name: Build and Push Frontend Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Build docker image
        run: docker build -t invenira/frontend:ci-build .

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.RELEASE_PKEY }}

      - uses: actions/setup-node@v4.2.0
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci

      - name: Create release and publish docker image
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}